#!/bin/bash
echo "Поиск учителя английского языка с опытом от 3 лет и IELTS C1..."
echo "Рекомендуемые платформы для поиска:"
echo "1. italki.com"
echo "2. Preply.com"
echo "3. Cambly.com"
echo "4. Skyeng.ru"
echo ""
echo "Критерии поиска:"
echo "- Опыт работы: от 3 лет"
echo "- Сертификат IELTS: уровень C1 (7.0-8.0 баллов)"
echo ""
echo "Пример запроса для поиска:"
echo "English teacher with 3+ years experience, IELTS C1 certified"
